module.exports = (grunt) ->

  grunt.registerTask "bower", ->
    
    src = grunt.source
    dist = grunt.config("dist")

    bower =
      note: "[DO NOT EDIT] This file was generated by http://github.com/jpillora/grunt-source-jslib"
      name: src.repoId or "jpillora/#{src.name}"
      version: src.version
      main: "#{dist}.js"
      description: src.description
      license: src.license
      ignore: ["*", "!bower.json", "!#{dist}.js", "!#{dist}.min.js"]

    grunt.file.write "bower.json", JSON.stringify bower, null, 2
